image: node:8.11.3-alpine
variables:
  TZ: Asia/Bangkok

stages:
- build
- docker
# - deploy

.workflow-branches: &workflow_branches
- master
# - dev

build:
  stage: build
  only: *workflow_branches
  cache:
    paths:
      - node_modules
  script:
  - npm prune
  - npm install
  - npm run build
  artifacts:
    expire_in: 30 min
    paths:
    - dist

docker:
  stage: docker
  only: *workflow_branches
  image: docker:stable
  services:
  - docker:dind
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE:latest